---
csv-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sensor_storage_temperature
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sensor_stock_levels
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sales

cleaned_csv-to-database:
  import:
    - import:
        dirpath: ./cleaned_data/
        file_extension: csv 
        prefix_filename: temp_agg
    - import:
        dirpath: ./cleaned_data/
        file_extension: csv 
        prefix_filename: stock_agg
    - import:
        dirpath: ./cleaned_data/
        file_extension: csv 
        prefix_filename: sales_agg

process_data:
  export:
    - export:
        host: s3
        bucket: ds-project-demo1
        prefix_filename: process_
  
predictions:
  export:
    - export:
        host: gsheet
        clear_sheet: false
        spreadsheet_id: 1AgkNJ9U2n3_7VeSGPCRhIzh-793N0O7PBeF-hfpYYmw
